## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np

In [8]:
def numpy_array(N):
    return np.arange(N-1, 0, -1)

In [9]:
numpy_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [15]:
def numpy_array(N):
    diagonal=np.diag(np.arange(N-1, 0, -1), k=0)
    return diagonal

In [19]:
print(numpy_array(10))
numpy_array(10).sum()

[[9 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]]


45

In [21]:
index = 0
sum_ = 0
for row in numpy_array(10):
    sum_ = sum_ + row[index]
    index = index + 1
sum_

45

## Задание 3
Решите систему уравнений:

    4x + 2y + z = 4
    x + 3y = 12
    5y + 4z = -3

In [24]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ] )

# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [23]:
# решение

from numpy import linalg

In [25]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [26]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задача 4 домашнего задания

![title](user_matrix.jpg)

Матрица в виде numpy array

In [30]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [31]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [32]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [36]:
# максимально похожий пользователь у которого косинус угла его вектора со сравниваемым стремится к 1
# запишем значеения векторов в словарь, пронумеровав пользователей
users={}
num=0
for row in users_stats:
    num+=1
    x = cosine(row, next_user_stats)
    users[num]=x
users    

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}

In [37]:
# найдем максимальное значение и выведем номер похожего пользователя
similar = max(users.items(), key=lambda x: x[1])
print (f'Максимально похожий пользователь по номером: {similar[0]}')

Максимально похожий пользователь по номером: 8
